Задание 7,8. Добавлена функциональность создания счёта и запроса баланса
gpb-it-factory/shevela-telegram-bot pull request #10
Opened 2024-06-15 13:53 UTC by IvanAlShell

2024-06-22 13:32 UTC, vaganov-vadim commented
А чего-то все тесты упали :(

2024-06-22 14:40 UTC, IvanAlShell commented
Вадим, привет! Да, странно, хотя локально все тесты проходят. Насколько я понял, падают из-за того, что не поднимается контекст, пока не получилось разобраться, в чате посоветовали запустить из-под Ubuntu, сегодня попробую, если не получится, то уже придется обращаться за помощью к тебе:)

2024-06-23 14:38 UTC, IvanAlShell commented
В связи с замечаниями по middle-сервису скорректирована логика - ответные сообщения клиенту формируются исходя из кодов ответов или ошибок от middle-сервиса, исправлены тесты

2024-06-25 16:29 UTC, vaganov-vadim requested changes
Привет! В целом - очень хорошая работа, есть применение паттернов, очень порадовало логирование. Есть какие-то моменты для улучшений, отметил их в комментах.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/resources/application-test.yml
> +botConfig: test
по идее тебе нет нужды так делать, можно просто пользоваться профилями спринга - ActiveProfiles. https://www.baeldung.com/spring-profiles

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/resources/application-test.yml
> +botConfig: test
И по сути название application-test - уже значит, что у тебя активный профиль "test".

2024-06-25 16:29 UTC, vaganov-vadim commented on src/main/java/gpb/itfactory/shevelatelegrambot/bot/config/BotInit.java
>  public class BotInit {
По наименованию класса не очень понятно, какая у него ответственность.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/main/java/gpb/itfactory/shevelatelegrambot/bot/config/BotConfig.java
> +@ConditionalOnProperty(value="botConfig", havingValue="production")
Конфигурацию лучше чаще всего оставлять единую, а в тестах подменять именно компонент, который использует эти настройки.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/main/java/gpb/itfactory/shevelatelegrambot/service/AccountService.java
> +    private final RestTemplate restTemplate;
Как вариант - сделать обёртку над клиентом, где уже будет вшит url и все необходимые конфигурационные элементы, чтобы ты вызывал уже готовую абстракцию. Также если абстрагировать интерфейсом, то проще будет подменять в тестах, например, т. к. это чисто транспорт, а не логика приложения.
+ если у тебя Spring Boot 3.0, то лучше заменить RestTemplate на RestClient.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/main/java/gpb/itfactory/shevelatelegrambot/service/AccountService.java
> +            log.info("Receive response from Middle Service: < create account > >  %s"
Логи - круто.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/UpdateDispatcherTest.java
> +@ActiveProfiles("test")
А, ну так уже и используется) Тогда тем более не совсем понял "production"-настройку.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/UpdateDispatcherTest.java
> +@EnableConfigurationProperties
А это для чего? Приложение должно подниматься и без дополнительных аннотаций в тестах. Суть такая - контекст должен подниматься аналогично тому, что и при нормальной работе приложения. Разве что какие-то компоненты подменяются на заглушки/моки/тестовые зависимости.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/handler/CreateAccountCommandHandlerTest.java
> +@ActiveProfiles("test")
Чаще всего лучше эти аннотации вынести на один базовый абстрактный класс для всех тестов. Так меньше вероятности пересоздания контекста спринга.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/handler/CurrentBalanceCommandHandlerTest.java
> +        String actualResult = currentBalanceCommandHandler.getCommand();
Ну по сути не очень полезный тест, потому что перепроверяем сами себя) Лучше проверять как-то вкупе с функциональностью - команда -> результат.

2024-06-25 16:29 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/integration/handler/CreateAccountCommandHandlerIT.java
> +    private Update update;
Лучше так не делать, т. к. состояние будет между тестами меняться и могут быть неприятные приколы. Лучше создавать модель в каждом тесте и не выносить это в общее поле.

2024-06-27 23:40 UTC, IvanAlShell commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/UpdateDispatcherTest.java
> +@EnableConfigurationProperties
Ввиду договоренностей что класс бота не тестируем, замысел был в том, чтобы не хранить BOT_NAME и BOT_TOKEN в репо и не инициализировать бин telegram-бота в тестовой конфигурации контекста (для этого и использовал @ConditionalOnProperty(value="botConfig", havingValue="production") соответствующие property и тестовые профили).
Сейчас добавил BOT_NAME и BOT_TOKEN в secrets GitHub Actions чтобы контекст подниматься как при нормальной работе приложения.

2024-06-27 23:50 UTC, IvanAlShell commented
Вадим, спасибо за быстрое конструктивное review и высокую оценку моей работы :) Исправлены замечания - заменил клиента на RestClient и сделал обертку, исправил название класса на BotInitializer, чтобы при тестах поднимался контекст как при нормальной работе приложения добавил имя и токен бота в secrets GitHub Actions, также скорректировал тесты

2024-06-29 09:57 UTC, vaganov-vadim commented on src/test/java/gpb/itfactory/shevelatelegrambot/bot/UpdateDispatcherTest.java
> +@EnableConfigurationProperties
Это можно чуть-чуть по-другому делать - сделать общий интерфейс и для тестов переопределить бин, чтобы он поднимался и что-то не делал, например. Но идею я понял.

2024-06-29 10:06 UTC, vaganov-vadim approved these changes

2024-06-29 10:32 UTC, merged